"""Durable workflow package (v0.6+).

PR-M1–M6: types, ports, memory store, runtime, worker, ops, façade.
Pilot P1–P2: ledger command log + SQL store (SQLite / Postgres).
"""

from impact_relay.workflows.commands import build_executable_command
from impact_relay.workflows.expense_to_receipt import (
    HandlerBundle,
    StepOutcome,
    freeze_command,
    step_classify,
    step_compose_send,
    step_evidence,
    step_intake,
    step_review,
)
from impact_relay.workflows.exceptions import (
    ClassifiedError,
    ErrorClass,
    WorkflowConflictError,
    WorkflowError,
    WorkflowNotFoundError,
    WorkflowStateError,
    classify_error,
    is_retryable,
    is_terminal,
)
from impact_relay.workflows.facade import (
    facade_mode,
    run_expense_approval_slice,
    run_expense_approval_slice_via_runtime,
)
from impact_relay.agents.ledger_binding import InMemoryLedgerBinding
from impact_relay.workflows.corrections import (
    build_reverse_command,
    build_supersede_command,
    step_after_ledger_correction,
    step_propose_correction,
)
from impact_relay.workflows.machine import (
    CORRECTION_TRANSITIONS,
    DEFAULT_RUN_STATUS,
    DIGEST_TRANSITIONS,
    EXPENSE_TO_RECEIPT_TRANSITIONS,
    HUMAN_GATE_STATES,
    assert_correction_transition,
    assert_digest_transition,
    assert_transition,
    can_correction_transition,
    can_digest_transition,
    can_transition,
    default_run_status,
    is_human_gate,
)
from impact_relay.workflows.scheduled_digest import (
    assemble_digests,
    step_assemble_and_privacy,
    step_complete_digest,
)
from impact_relay.workflows.ports import (
    Clock,
    ExecutorFactory,
    IdGenerator,
    LedgerBinding,
    SystemClock,
    UuidIdGenerator,
    WorkflowStore,
)
from impact_relay.workflows.runtime import WorkflowRuntime, default_executor_factory
from impact_relay.workflows.store_memory import InMemoryWorkflowStore
from impact_relay.workflows.store_sql import SqlWorkflowStore, open_sql_store
from impact_relay.workflows.ops import (
    OperatorCase,
    approval_from_dict,
    list_blocked,
    list_operator_cases,
    load_ops_session,
    save_ops_session,
    seed_session_to_wait,
    signal_approval_and_pump,
)
from impact_relay.workflows.guards import DurabilityGuardError
from impact_relay.workflows.worker import TickResult, WorkerConfig, WorkflowWorker
from impact_relay.workflows.types import (
    CLAIMABLE_RUN_STATUSES,
    TERMINAL_RUN_STATUSES,
    AdvanceCommitBundle,
    ExecutableCommand,
    FrozenProposedCommand,
    RetryPolicy,
    SignalConsumeResult,
    SignalType,
    StepResult,
    WorkflowEvent,
    WorkflowEventType,
    WorkflowEventWrite,
    WorkflowInstance,
    WorkflowRunStatus,
    WorkflowSignal,
    WorkflowState,
    WorkflowType,
)

__all__ = [
    "AdvanceCommitBundle",
    "CLAIMABLE_RUN_STATUSES",
    "CORRECTION_TRANSITIONS",
    "ClassifiedError",
    "Clock",
    "DEFAULT_RUN_STATUS",
    "DIGEST_TRANSITIONS",
    "DurabilityGuardError",
    "EXPENSE_TO_RECEIPT_TRANSITIONS",
    "ErrorClass",
    "ExecutableCommand",
    "ExecutorFactory",
    "FrozenProposedCommand",
    "HUMAN_GATE_STATES",
    "HandlerBundle",
    "IdGenerator",
    "InMemoryLedgerBinding",
    "InMemoryWorkflowStore",
    "LedgerBinding",
    "SqlWorkflowStore",
    "OperatorCase",
    "RetryPolicy",
    "SignalConsumeResult",
    "SignalType",
    "StepOutcome",
    "StepResult",
    "SystemClock",
    "TERMINAL_RUN_STATUSES",
    "TickResult",
    "UuidIdGenerator",
    "WorkerConfig",
    "WorkflowConflictError",
    "WorkflowError",
    "WorkflowEvent",
    "WorkflowEventType",
    "WorkflowEventWrite",
    "WorkflowInstance",
    "WorkflowNotFoundError",
    "WorkflowRunStatus",
    "WorkflowRuntime",
    "WorkflowSignal",
    "WorkflowState",
    "WorkflowStateError",
    "WorkflowStore",
    "WorkflowType",
    "WorkflowWorker",
    "approval_from_dict",
    "assemble_digests",
    "assert_correction_transition",
    "assert_digest_transition",
    "assert_transition",
    "build_executable_command",
    "build_reverse_command",
    "build_supersede_command",
    "can_correction_transition",
    "can_digest_transition",
    "can_transition",
    "classify_error",
    "default_executor_factory",
    "default_run_status",
    "facade_mode",
    "freeze_command",
    "is_human_gate",
    "is_retryable",
    "is_terminal",
    "step_after_ledger_correction",
    "step_assemble_and_privacy",
    "step_complete_digest",
    "step_propose_correction",
    "list_blocked",
    "list_operator_cases",
    "load_ops_session",
    "open_sql_store",
    "run_expense_approval_slice",
    "run_expense_approval_slice_via_runtime",
    "save_ops_session",
    "seed_session_to_wait",
    "signal_approval_and_pump",
    "step_classify",
    "step_compose_send",
    "step_evidence",
    "step_intake",
    "step_review",
]
