"""Durable workflow package (v0.6+).

PR-M1: types, ports, exception taxonomy.
Later PRs: memory store, runtime, worker, postgres.
"""

from impact_relay.workflows.commands import build_executable_command
from impact_relay.workflows.expense_to_receipt import (
    HandlerBundle,
    StepOutcome,
    freeze_command,
    step_classify,
    step_compose_send,
    step_evidence,
    step_intake,
    step_review,
)
from impact_relay.workflows.exceptions import (
    ClassifiedError,
    ErrorClass,
    WorkflowConflictError,
    WorkflowError,
    WorkflowNotFoundError,
    WorkflowStateError,
    classify_error,
    is_retryable,
    is_terminal,
)
from impact_relay.workflows.facade import (
    facade_mode,
    run_expense_approval_slice,
    run_expense_approval_slice_via_runtime,
)
from impact_relay.agents.ledger_binding import InMemoryLedgerBinding
from impact_relay.workflows.machine import (
    DEFAULT_RUN_STATUS,
    EXPENSE_TO_RECEIPT_TRANSITIONS,
    HUMAN_GATE_STATES,
    assert_transition,
    can_transition,
    default_run_status,
    is_human_gate,
)
from impact_relay.workflows.ports import (
    Clock,
    ExecutorFactory,
    IdGenerator,
    LedgerBinding,
    SystemClock,
    UuidIdGenerator,
    WorkflowStore,
)
from impact_relay.workflows.runtime import WorkflowRuntime, default_executor_factory
from impact_relay.workflows.store_memory import InMemoryWorkflowStore
from impact_relay.workflows.types import (
    CLAIMABLE_RUN_STATUSES,
    TERMINAL_RUN_STATUSES,
    AdvanceCommitBundle,
    ExecutableCommand,
    FrozenProposedCommand,
    RetryPolicy,
    SignalConsumeResult,
    SignalType,
    StepResult,
    WorkflowEvent,
    WorkflowEventType,
    WorkflowEventWrite,
    WorkflowInstance,
    WorkflowRunStatus,
    WorkflowSignal,
    WorkflowState,
    WorkflowType,
)

__all__ = [
    "AdvanceCommitBundle",
    "CLAIMABLE_RUN_STATUSES",
    "ClassifiedError",
    "Clock",
    "DEFAULT_RUN_STATUS",
    "EXPENSE_TO_RECEIPT_TRANSITIONS",
    "ErrorClass",
    "ExecutableCommand",
    "ExecutorFactory",
    "FrozenProposedCommand",
    "HUMAN_GATE_STATES",
    "HandlerBundle",
    "IdGenerator",
    "InMemoryLedgerBinding",
    "InMemoryWorkflowStore",
    "LedgerBinding",
    "RetryPolicy",
    "SignalConsumeResult",
    "SignalType",
    "StepOutcome",
    "StepResult",
    "SystemClock",
    "TERMINAL_RUN_STATUSES",
    "UuidIdGenerator",
    "WorkflowConflictError",
    "WorkflowError",
    "WorkflowEvent",
    "WorkflowEventType",
    "WorkflowEventWrite",
    "WorkflowInstance",
    "WorkflowNotFoundError",
    "WorkflowRunStatus",
    "WorkflowRuntime",
    "WorkflowSignal",
    "WorkflowState",
    "WorkflowStateError",
    "WorkflowStore",
    "WorkflowType",
    "assert_transition",
    "build_executable_command",
    "can_transition",
    "classify_error",
    "default_executor_factory",
    "default_run_status",
    "facade_mode",
    "freeze_command",
    "is_human_gate",
    "is_retryable",
    "is_terminal",
    "run_expense_approval_slice",
    "run_expense_approval_slice_via_runtime",
    "step_classify",
    "step_compose_send",
    "step_evidence",
    "step_intake",
    "step_review",
]
